name: 7zip-desktop
version: "16.02"
summary: 7Zip Desktop
description: |
  7-Zip is a file archiver with a high compression ratio, this package also includes the graphic frontend for maximum cosiness on the desktop

confinement: devmode

apps:
  7zip-desktop:
    command: /usr/local/bin/7zFM

parts:
  7zip-desktop:
    plugin: dump 
    source-type: git
    source: git://github.com/ErnyTech/p7zip.git
    
    override-pull: |
      snapcraftctl pull
      cp makefile.linux_amd64_asm makefile.machine
      sed -i 's/x86_64-linux-gnu//g' CPP/7zip/*/*/*.depend
      rm GUI/kde4/p7zip_compress.desktop
      cd Utils
      sed -i 's/_do_not_use//g' generate.py
      ./generate.py
      
    override-build: |
      snapcraftctl build
      make 7zFM 7zG
      make install DEST_DIR="$SNAPCRAFT_PART_INSTALL"
      
    build-packages:
      - gcc
      - make
      - libwxgtk3.0-dev
      - yasm
      - libice6
      - libsm6
      - libx11-6
      - libxau-dev
