name: p7zip-desktop
version: "16.02"
summary: 7Zip Desktop
description: |
  7-Zip is a file archiver with a high compression ratio, this package also includes the graphic frontend for maximum cosiness on the desktop

confinement: devmode

apps:
  p7zip-desktop:
    command: /usr/local/bin/7zFM

parts:
  p7zip-desktop:
    plugin: dump 
    source-type: git
    source: git://github.com/ErnyTech/p7zip.git
    
    override-pull: |
      snapcraftctl pull
      
      if [ "$SNAP_ARCH" = "arm64" ]; then
        cp makefile.linux_amd64_asm makefile.machine
      fi
      
      if [ "$SNAP_ARCH" = "i386" ]; then
        cp makefile.linux_x86_asm_gcc_4.X makefile.machine
      fi
      
      if [ "$SNAP_ARCH" = "arm64" ] || [ "$SNAP_ARCH" = "armhf" ]; then
        cp makefile.linux_any_cpu_gcc_4.X makefile.machine
      fi
      
      cd Utils
      ./generate.py
      
    override-build: |
      snapcraftctl build
      make 7zFM 7zG
      make install DEST_DIR="$SNAPCRAFT_PART_INSTALL"
      
    build-packages:
      - gcc
      - make
      - libwxgtk3.0-dev
      - yasm
      - libice6
      - libsm6
      - libx11-6
      - libxau-dev
