name: p7zip-desktop
version: "16.02"
summary: 7Zip Desktop
icon: GUI/p7zip_32.png
grade: stable
description: |
  7-Zip is a file archiver with a high compression ratio, this package also includes the graphic frontend for maximum cosiness on the desktop

confinement: strict

apps:
  p7zip-desktop:
    command: usr/local/bin/7zDesktop
    desktop: usr/share/applications/7zFM.desktop
    plugs:
    - x11
    - wayland 
    - desktop
    - desktop-legacy
    - home

parts:
  p7zip-desktop:
    plugin: dump 
    source: .
    
    override-pull: |
      snapcraftctl pull
      echo "Icon=/snap/p7zip-desktop/current/meta/gui/icon.png" >> 7zFM.desktop
      cd Utils
      ./generate.py
      
    override-build: |
      rm -rf "$SNAPCRAFT_PART_INSTALL/*"
      make 7zFM 7zG
      make install DEST_DIR="$SNAPCRAFT_PART_INSTALL"
      mkdir -p "$SNAPCRAFT_PART_INSTALL/usr/share/applications"
      cp 7zFM.desktop "$SNAPCRAFT_PART_INSTALL/usr/share/applications/7zFM.desktop"
      cp 7zDesktop "$SNAPCRAFT_PART_INSTALL/usr/local/bin/7zDesktop"
      chmod +x "$SNAPCRAFT_PART_INSTALL/usr/local/bin/7zDesktop"
      chmod +x "$SNAPCRAFT_PART_INSTALL/usr/local/bin/p7zipForFilemanager"
      
    build-packages:
      - gcc
      - g++
      - make
      - libwxgtk3.0-dev
      - yasm
      - python
      
    stage-packages:
      - libice6
      - libsm6
      - libx11-6
      - libxau-dev
      - libgdk-pixbuf2.0-0
      - zlib1g
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libxxf86vm1
      - libatk1.0-0
      - libcairo2
      - libdatrie1
      - libfontconfig1
      - libgtk2.0-0
      - libgraphite2.so.3
      - libharfbuzz0b
      - libnotify4
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libthai0
      - libwxbase3.0-0v5
      - libxcb-render0
      - libxcb-shm0
